spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk_db
spring.datasource.username=helpdesk_user
spring.datasource.password=helpdesk_pass

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration