name: Backend CI

on:
  pull_request:
    branches: [ main ]

  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build e testes
        run: mvn clean verify
        working-directory: backend
